## Poker Hand Data Set

### Датасет представляет из себя набор из 5 карт стандартной колоды из 52 карт. Каждая карта имеет 2 атрибута: Масть и ранг. Эта информация предоставлена в виде первых 10ти столбцов датасета. 11й столбец представляет собой силу руки, которая предоставляется в виде значения от 0 до 9, где 0 - это отсутствие комбинации, а 9 - Флеш Рояль. Необходимо предсказать силу руки, имея данные о 5ти картах в руке

In [1]:
import pandas as pd

In [2]:
data_train = pd.read_csv('poker-hand-training-true.csv',sep = ';', header = None)
#data_train.head()
data_test = pd.read_csv('poker-hand-testing.csv',sep = ';', header = None)

In [3]:
data_train.head()

0   1   2   3   4   5   6   7   8   9   10
0   1  10   1  11   1  13   1  12   1   1   9
1   2  11   2  13   2  10   2  12   2   1   9
2   3  12   3  11   3  13   3  10   3   1   9
3   4  10   4  11   4   1   4  13   4  12   9
4   4   1   4  13   4  12   4  11   4  10   9

In [4]:
drop = [10]
X_train = data_train.drop(drop,axis=1)
Y_train = data_train[10]

X_test = data_test.drop(drop,axis=1)
Y_test = data_test[10]


In [5]:
X_test

0   1  2   3  4   5  6   7  8   9
0       1   1  1  13  2   4  2   3  1  12
1       3  12  3   2  3  11  4   5  2   5
2       1   9  4   6  1   4  3   2  3   9
3       1   4  3  13  2  13  2   1  3   6
4       3  10  2   7  1   2  2  11  4   9
...    ..  .. ..  .. ..  .. ..  .. ..  ..
999995  3   1  1  12  2   9  4   9  2   6
999996  3   3  4   5  2   7  1   4  4   3
999997  1  11  4   7  3   9  1  13  2   7
999998  3  11  1   8  1   1  3  13  2   8
999999  2   5  2   9  4   9  2   3  3   3

[1000000 rows x 10 columns]

In [6]:
Y_test

0         0
1         1
2         1
3         1
4         0
         ..
999995    1
999996    1
999997    1
999998    1
999999    2
Name: 10, Length: 1000000, dtype: int64

In [7]:
Y_train

0        9
1        9
2        9
3        9
4        9
        ..
25005    0
25006    1
25007    1
25008    1
25009    1
Name: 10, Length: 25010, dtype: int64

In [8]:
! pip install lightgbm
! pip install --upgrade catboost==0.25

In [9]:
from sklearn.metrics import *

In [13]:
print(y_pred[:, 1].astype('float64'))
print(Y_test.to_numpy().astype('float64'))
print('LightGBM: ',roc_auc_score(Y_test.to_numpy().astype('float64'), y_pred,multi_class='ovr'))

[0.20898508 0.21283818 0.43599216 ... 0.99999996 0.05715268 0.02518119]
[0. 1. 1. ... 1. 1. 2.]
LightGBM:  0.6285260222080155


In [31]:
clf_cb = CatBoostClassifier(iterations=300, logging_level='Silent')
clf_cb.fit(X_train, Y_train)
y_pred = clf_cb.predict_proba(X_test)


In [32]:
print(type(y_pred))
print(type(Y_test.to_numpy()))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [33]:
print(y_pred[:, 1].astype('float64'))
print(Y_test.to_numpy().astype('float64'))
print('Catboost: ',roc_auc_score(Y_test.to_numpy().astype('float64'), y_pred,multi_class='ovr'))

[0.51217451 0.33940045 0.56129722 ... 0.34425004 0.29391832 0.43768106]
[0. 1. 1. ... 1. 1. 2.]
Catboost:  0.9045639443290184


In [52]:
from sklearn.ensemble import  GradientBoostingClassifier


In [53]:
reg = GradientBoostingClassifier(max_depth=1, learning_rate=0.1, warm_start=True, n_estimators = 300)
reg.fit(X_train, Y_train)
y_pred = reg.predict(X_test)


In [63]:
print(type(y_pred))
print(type(Y_test.to_numpy()))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [65]:
print(y_pred)
print(Y_test.to_numpy())
print('sklearn: ',roc_auc_score(Y_test.to_numpy(), y_pred,multi_class='ovr'))

[0 0 0 ... 0 1 0]
[0 1 1 ... 1 1 2]


ValueError: multi_class must be in ('ovo', 'ovr')