# <center> Homework 1 </center>

# 0. Где мы сейчас?
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Jupyter_logo.svg/1200px-Jupyter_logo.svg.png" width="150">

[Jupyter Notebook](https://jupyter.org/) - интерактивная среда для запуска программного кода в браузере. Удобный инструмент для анализа данных, который используется многими специалистами по data science. Позволяет выполнять отдельные ячейки с кодом, а не всю программу сразу, что очень удобно при знакомстве с данными.

# 1. Python
> Python - это свободный интерпретируемый объектно-ориентированный расширяемый встраиваемый язык программирования очень высокого уровня 

>*(Г.Россум, Ф.Л.Дж.Дрейк, Д.С.Откидач "Язык программирования Python").*

А если без цитат, то питон - это просто очень крутой язык, созданный в 1991 году [Великодушным пожизненным диктатором](https://ru.wikipedia.org/wiki/%D0%92%D0%B5%D0%BB%D0%B8%D0%BA%D0%BE%D0%B4%D1%83%D1%88%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D0%B6%D0%B8%D0%B7%D0%BD%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D0%BA%D1%82%D0%B0%D1%82%D0%BE%D1%80) Гвидо ван Россумом и названный в честь любимого им шоу [Monty Python's Flying Circus](https://en.wikipedia.org/wiki/Monty_Python%27s_Flying_Circus)

<img src="https://advancelocal-adapter-image-uploads.s3.amazonaws.com/image.oregonlive.com/home/olive-media/width2048/img/tv/photo/2018/10/10/montycastjpg-7ef393e2355a42aa.jpg" width="300">

# 2. Anaconda

<img src="https://cdn-images-1.medium.com/max/1600/0*MVkCW8_Bmj-nuAnI.png" width="300">

[Сборка Anaconda](https://www.anaconda.com/products/individual) включает очень много полезных библиотек для анализа данных. 

Среди наиболее популярных библиотек:
 - <a href="http://numpy.org">Numpy</a> - это один из основных пакетов для математических вычислений. Он содержит средства для работы с многомерными массивами и высокоуровневыми математическими функциями
 - <a href="https://www.scipy.org/">SciPy</a> - научные вычисления. Методы оптимизации, интегрирования, модули обработки сигналов и изображений, статистика, линейная алгебра, сплайны, кластеризация и многое другое
 -  <a href="http://pandas.pydata.org/">Pandas</a> - основная библиотека для обработки и анализа данных. Предназначена для данных разной природы - матричных, панельных данных, временных рядов. Претендует на звание самого мощного и гибкого средства для анализа данных с открытым исходным кодом
 - <a href="http://scikit-learn.org/stable/">Scikit-learn</a> - реализация очень многих методов машинного обучения с отличной документацией. 
 - <a href="http://http://matplotlib.org/">matplotlib</a> - хорошая библиотека для визуализации данных

# 3. Задачки

## Задача 1
$N$ хоббитов делят $K$ кусков эльфийского хлеба поровну, не делящийся нацело остаток остается в корзинке у Сэма. Напишите функцию, которая принимает на вход параметры $N$ и $K$ и возвращает два числа: $x$ - cколько кусков эльфиского хлеба достанется каждому хоббиту, и $y$ - сколько кусков остаётся в корзинке.

In [4]:
def share_bread(N, K):
    x = K // N
    y = K % N
    # your code here
    return x, y

# если в функции всё верно, то после выполнения этой строчки, не должно выскакивать ошибок
assert share_bread(N=3, K=14) == (4, 2)

## Задача 2

В копях Мории хоббиты нашли стену, на которой высечены разные натуральные числа. Согласно древним сказаниям, это даты сражений. Хоббиты знают, что сражения происходили только по високосным годам. Помогите хоббитам определить, является ли год с данным числом датой великого сражения. Если это так, то верните строку "YOU SHALL PASS", иначе верните "YOU SHALL NOT PASS". Напомним, что в соответствии с хоббитским календарем, год является високосным, если его номер кратен 4, но не кратен 100, а также если он кратен 400.

In [12]:
def leap_year(year):
    text_result = 'YOU SHALL NOT PASS'
    if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
        text_result = 'YOU SHALL PASS'
    # your code here
    return text_result

assert leap_year(5) == 'YOU SHALL NOT PASS'

## Задача 3
<img src="http://i0.kym-cdn.com/photos/images/original/001/187/255/5e9.gif" width=300>
Для могущественного магического ритуала Гендальфу необходимо быстро подсчитывать площадь своего амулета, который умеет менять размеры. Известно, что амулет имеет форму треугольника и Гендальф знает длину каждой из сторон. Напишите функцию, которая считает площадь амулета по трем сторонам.  

Подсказка: используйте формулу Герона
$$ S = \sqrt{p(p-a)(p-b)(p-c)} $$
$$ p = \frac{a + b + c}{2}$$


In [13]:
def amulet_area(a, b, c):
    # your code here
    p = (a + b + c) / 2
    S = (p * (p - a) * (p - b) * (p - c))**0.5
    return S

assert amulet_area(3, 4, 5) == 6

## Задача 4

Хоббиты собираются пешком идти до Мордора и им нужно подсчитать расстояние, которое им предстоит пройти. Хоббиты смогли вспомнить сразу несколько метрик расстояния: евклидово, манхэттена и косинусное, так что ваша задача - напистаь функцию под каждую из них. Важное условие - используйте только базовые функции numpy для решения.


* Евклидово расстояние
$$ d(a, b) = \sqrt{\sum_i (a_i - b_i)^2} $$
* Расстояние Манхэттена
$$ d(a, b) = \sum_i |a_i - b_i| $$
* Косинусное расстояние
$$ d(a, b) = 1 - \frac{a^\top b}{||a||_2\cdot||b||_2}$$

In [21]:
def cal_euclidean(a, b):
    ## Your code here
    square = np.square(a - b)
    sum_square = np.sum(square)
    distance = np.sqrt(sum_square)
    return distance


def cal_manhattan(a, b):
    ## Your code here
    distance = np.sum(np.abs(a - b))
    return distance


def cal_cosine(a, b):
    ## Your code here
    distance = 1- (np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))
    return distance



In [22]:
a = np.random.randint(-10, 10, size=10)
b = np.random.randint(-10, 10, size=10)
print(cal_euclidean(a, b))
print(cal_manhattan(a, b))
print(cal_cosine(a, b))

30.033314835362415
84
1.7083384149804566


## Задача 5

Ну и напоследок, еще немного практики numpy, без которой не обходится ни один хоббит.


Создайте случайный array (`np.random.rand()`) длинной 100. Преобразуйте его так, чтобы
* Максимальный элемент(ы) был равен 1
* Минимальный элемент(ы) был равен 0
* Остальные элементы в итнтервале от 0 до 1 остаются прежними

In [2]:
import numpy as np
my_array = array = np.random.rand(100)
## Your code here
print(np.max(my_array), np.min(my_array))
print(my_array)

0.9970595439083487 0.0128530445684496
[0.48359736 0.82482852 0.79613977 0.63084163 0.29890044 0.57185951
 0.1514151  0.76344414 0.70806656 0.29702719 0.4204985  0.58590686
 0.63716299 0.0746223  0.18981993 0.58190002 0.96740862 0.54402777
 0.54211921 0.05815228 0.45134898 0.09108616 0.88468005 0.07087774
 0.01285304 0.02703113 0.60164535 0.20282218 0.56533481 0.98007855
 0.81441491 0.1335386  0.43628212 0.9256975  0.37992199 0.84178738
 0.53293607 0.40800366 0.98070534 0.47236155 0.75107283 0.99705954
 0.46646649 0.46401185 0.98041522 0.54750337 0.85340865 0.37050055
 0.92824039 0.63428936 0.51644539 0.07159218 0.90851939 0.37933068
 0.1852695  0.14962221 0.12947664 0.49886262 0.13512097 0.99216941
 0.43082873 0.70615242 0.91550557 0.37095626 0.56427442 0.97725016
 0.64422737 0.40431716 0.58545872 0.08968545 0.46096628 0.60625804
 0.45939812 0.99127978 0.1528804  0.2110025  0.12579447 0.41175825
 0.35121607 0.61223514 0.01755139 0.13950099 0.18705558 0.10087113
 0.42652265 0.70111013 0

Создайте array размером $5 \times 6$ с целыми числами в интервале [0,50]. Напечатайте колонку, которая содержит максимальный элемент полученной матрицы 

In [ ]:
import numpy as np

my_array = np.random.randint(0,50,(5,6))## Your code here
selected_column =my_array[ np.argmax(np.max(my_array, axis=1))]
print('Shape: ',my_array.shape)
print('Array')
print(my_array)
print(selected_column)

Напишите функцию, которая принимает на вохд матрицу (array) X и возвращает все её уникальные строки в виде новой матрицы.

In [3]:
def get_unique_rows(X):
    X_unique = np.unique(X, axis=0)
    return X_unique

In [5]:
X = np.random.randint(4, 6, size=(10,3))
print(X)

[[4 4 5]
 [4 5 4]
 [5 4 4]
 [4 4 4]
 [5 5 5]
 [4 5 5]
 [5 4 5]
 [5 5 4]
 [4 4 4]
 [5 5 5]]


In [4]:
get_unique_rows(X)

NameError: name 'X' is not defined